In [1]:
import numpy as np

In [4]:
var=np.array([1,2,3,4,5])
print(var)
print(var.dtype)
print(type(var))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [6]:
var=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(var)
print(var.dtype)
print(type(var))

[[1 2 3 4 5]
 [4 5 6 7 8]]
int32
<class 'numpy.ndarray'>


In [10]:
var=np.array([[[1,2,3,4,5],[4,5,6,7,8]]])
print(var)
print(var.dtype)
print(type(var))
print("Dimension:",var.ndim)

[[[1 2 3 4 5]
  [4 5 6 7 8]]]
int32
<class 'numpy.ndarray'>
Dimension: 3


In [8]:
                                                            #To make the multiple dimension in a row with func

In [14]:
var_1=np.array([1,2,3,4,5],ndmin=10)
print(var_1)
print(type(var_1))
print(var_1.dtype)
print("Dimension:",var.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
<class 'numpy.ndarray'>
int32
Dimension: 3


In [15]:
                                                                        #Zero Array

In [24]:
var_2=np.zeros((4,2))
print(var_2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
var_2=np.ones((4,3))
print(var_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
var_3=np.empty((3,4))
print(var_3)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
var_4=np.eye(3)
var_4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
var_5=np.arange((10))
var_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
var_6=np.linspace(1,19,num=3)
var_6

array([ 1., 10., 19.])

In [40]:
                                                            #Random and their function

In [46]:
random=np.random.randn(5)
random

array([-0.3658147 , -0.32894384,  1.15993242, -1.5418408 ,  0.10176085])

In [47]:
random=np.random.ranf(5)
random

array([0.43725487, 0.59248868, 0.77226636, 0.17801469, 0.81119277])

In [61]:
random=np.random.randint(0,5,(2,2))
random

array([[4, 3],
       [4, 3]])

In [69]:
var_11=np.array([[1,2,3,4],[5,6,7,8]])
print(var_11)
print(var_11.dtype)
new_type=var_11.astype(float)
print(new_type.dtype)

[[1 2 3 4]
 [5 6 7 8]]
int32
float64


In [72]:
var=np.array([[1,2,3],[12,14,16]])
print(var.shape)

(2, 3)


In [79]:
var=np.array([1,2,3,4,5,6,7,8,9])
new_value=var.reshape(3,3)
new_value

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
var=np.array([1,2,3,4,5,6,7,8,9,5])
new_value=var.reshape(5,2)
new_value

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 5]])

In [81]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var3.reshape(2,3,2)
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [82]:
print(x.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
