In [1]:
import numpy as np

In [7]:
var=np.array([[1,2,3],[4,5,6]])
copy=var.copy()
print(copy)

[[1 2 3]
 [4 5 6]]


In [8]:
var=np.array([[1,2,3],[4,5,6]])
copy=var.view()
print(copy)

[[1 2 3]
 [4 5 6]]


In [ ]:
                    #it will copy the elemenet of the var array but when we change the element the origna var gona change

In [13]:
var=np.array([[1,2,3],[4,5,6]])
copy=var.view()
copy[1,0]=11
print(var)
print()
print(copy)


[[ 1  2  3]
 [11  5  6]]

[[ 1  2  3]
 [11  5  6]]


In [ ]:
                                            #it will copy the elemenet of the var array but when we change the element the origna var never gona change

In [16]:
var=np.array([[1,2,3],[4,5,6]])
copy=var.copy()
copy[1,0]=22
print(var)
print()
print(copy)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [22  5  6]]


In [17]:
                                                           #join two D array

In [25]:
var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[11,12,13],[14,15,16]])
result=np.concatenate((var1,var2),axis=1)
print(result)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [26]:
var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[11,12,13],[14,15,16]])
result=np.concatenate((var1,var2),axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


                                                                Split array

In [32]:
f=np.array([[1,2,3,4],[5,6,7,8]])
n=np.array([[11,12,13,14],[16,17,18,19]])
x=np.array_split(f,3)
print(x)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]


In [35]:
                                                                            #Search and sort

In [36]:
import numpy as np

In [37]:
var=np.array([1,2,3,4,5,6,7,5,5])
result=np.where(var==5)
print(result)

(array([4, 7, 8], dtype=int64),)


In [42]:
var=np.array([1,2,3,4,5,6,7,5,5])
result=np.where(var==5)
print(result)

(array([4, 7, 8], dtype=int64),)


In [47]:
var=[1,2,3,4,5,1,2,1,1,1]
new=np.array(var)
result=np.where(new==1)
print(result)


(array([0, 5, 7, 8, 9], dtype=int64),)


In [48]:
                                                                    #Sort

In [52]:
var=[1,11,42,1,2,9,4,17,3,5]
new=np.array(var)
print("Not Sorted:",new)
print()
result=np.sort(new)
print("Sorted Aaray:",result)

Not Sorted: [ 1 11 42  1  2  9  4 17  3  5]

Sorted Aaray: [ 1  1  2  3  4  5  9 11 17 42]


In [53]:
#Some Functionlike shuffle / unique / resize/ flatten/ ravel

In [61]:
var=np.array([[1,2,3,4,5],[6,7,8,9,10]])
np.random.shuffle(var)
var

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [65]:
new=np.array([1,2,3,4,5,1,2,8,2,0,2])
result=np.unique(new,return_counts=True,return_index)
result

(array([0, 1, 2, 3, 4, 5, 8]),
 array([9, 0, 1, 2, 3, 4, 7], dtype=int64),
 array([1, 2, 4, 1, 1, 1, 1], dtype=int64))

In [66]:
                                                                #Insert and delet

In [73]:
var=np.array([1,2,3,4,5])
print(var)
print(var.dtype)
print(np.insert(var,(1,3),222))

[1 2 3 4 5]
int32
[  1 222   2   3 222   4   5]


In [74]:
print(np.delete(var,(1,3)))

[1 3 5]
