In [1]:
import numpy as np

                                            One Dimension Array

In [31]:
var=np.array([1,2,3,4,5])
print(var)
print(type(var))
print("Dimension:",var.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Dimension: 1


                                                Two Dimension Array

In [38]:
var2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(var2)
print(type(var2))
print("Dimension:",var2.ndim)

[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
Dimension: 2


                                                    Three Dimension Array

In [40]:
var3=np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
print(var3)
print("Type:",type(var3))
print("Dimension:",var3.ndim)

[[[ 1  2  3  4  5]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
Type: <class 'numpy.ndarray'>
Dimension: 3


                                                            MultiDimensional-Array

In [42]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print("Dimension:",arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
Dimension: 10


                                            Array filled with 0

In [48]:
zero_Arr=np.zeros(4)
ar_zeros=np.zeros((3,4))
print(ar_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


                                                Array filled with `1

In [53]:
zero_Arr=np.ones(4)
print(zero_Arr)
print()
Multi_one=np.ones((3,4))
print(Multi_one)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


                                                        Array fill with empty

In [57]:
empty_arr=np.empty(3)
print(empty_arr)

[ 1.46819843e-311  0.00000000e+000 -4.94065646e-324]


                                                                    Range Array

In [60]:
arrange_arr=np.arange(4)
print(arrange_arr)

[0 1 2 3]


                                                        Daigonal Element 1

In [64]:
daingonal_Arr=np.eye(3,4)
print(daingonal_Arr)
print(daingonal_Arr.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
2


                                                    Special value in range

In [69]:
linespace=np.linspace(1,10,num=3)
print(linespace)

[ 1.   5.5 10. ]


                                                            Random number in  numpy

                                                        random.rand

In [80]:
var=np.random.rand(2,2)
print(var)

[[0.9489615  0.16398229]
 [0.55258226 0.60359308]]


                                                        randn

In [83]:
var=np.random.randn(2,4)
var

array([[ 1.23438522,  0.41632518,  0.28061653, -0.53833136],
       [ 1.2392863 ,  1.17675348,  0.11467185,  3.566596  ]])

                                                            ranf

In [87]:
var=np.random.ranf(2)
print(var)

[0.82356138 0.46296049]


                                                            rand_integers

In [99]:
var=np.random.randint(1,10,(4,4))
var

array([[6, 8, 3, 2],
       [4, 2, 8, 5],
       [9, 6, 7, 3],
       [1, 3, 5, 1]])

In [104]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x.dtype)
print(x)

int8
[1 2 3 4]


In [107]:
x1=np.array([1,2,3,4],dtype='f')
print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4.]


In [109]:
x1=np.array([1,2,3,4])
new_1=x1.astype(float)
print(x1)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


                                                            Shape and Reshape

In [116]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print("value",var)
print("Shape",var.shape)

value [[1 2 3 4]
 [5 6 7 8]]
Shape (2, 4)


In [121]:
var1=np.array([1,2,3,5],ndmin=5)
print(var1)
print(var.shape)

[[[[[1 2 3 5]]]]]
(2, 4)


                                                                        Reshape

In [128]:
var=np.array([1,2,3,4,5,6,7,8,9])
x=var.reshape(3,3)
print(x)
print(x.ndim)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


                                                    Multi-Dimensional

In [130]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var3.reshape(2,3,2)
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


                                                                Back to one Dimension

In [131]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var3.reshape(2,3,2)
print(x)
print()
z=x.reshape(-1)
print(z)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
