In [1]:
import numpy as np

In [2]:
var=np.array([1,2,3,4,5])
print(var*2)

[ 2  4  6  8 10]


In [3]:
var=np.array([1,2,3,4,5])
print(var+2)

[3 4 5 6 7]


In [4]:
var=np.array([1,2,3,4,5])
print(var-2)

[-1  0  1  2  3]


In [5]:
var=np.array([1,2,3,4,5])
print(var/2)

[0.5 1.  1.5 2.  2.5]


In [6]:
var=np.array([1,2,3,4,5])
print(var%2)

[1 0 1 0 1]


In [8]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
print(var1*2)

[[ 2  4  6  8]
 [ 8 10 12 14]]


In [9]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
print(var1+2)

[[3 4 5 6]
 [6 7 8 9]]


In [10]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
print(var1-2)

[[-1  0  1  2]
 [ 2  3  4  5]]


In [11]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
print(var1/2)

[[0.5 1.  1.5 2. ]
 [2.  2.5 3.  3.5]]


In [12]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
print(var1*2)

[[1 0 1 0]
 [0 1 0 1]]


In [13]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.add(var1,var2))

[[ 2  4  6  8]
 [ 8 10 12 14]]


In [15]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.subtract(var1,var2))

[[0 0 0 0]
 [0 0 0 0]]


In [16]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.divide(var1,var2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.multiply(var1,var2))

[[ 1  4  9 16]
 [16 25 36 49]]


In [18]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.mod(var1,var2))

[[0 0 0 0]
 [0 0 0 0]]


In [19]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])
var2=np.array([[1,2,3,4],[4,5,6,7,]])
print(np.reciprocal(var1,var2))

[[1 0 0 0]
 [0 0 0 0]]


In [25]:
var1=np.array([[1,2,3,4],[4,5,6,7,]])

print(value)

1


In [29]:
print(np.shape(var1,))

(2, 4)


In [38]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.min(var2),np.argmin(var2)
value

(3, 2)

In [39]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.max(var2),np.argmax(var2)
value

(12, 1)

In [52]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.max(var2,axis=1)
value

array([12,  7])

In [51]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.min(var2,axis=0)
value

array([4, 5, 3, 4])

In [53]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
print(np.sin(var2))

[[-0.54402111 -0.53657292  0.14112001 -0.7568025 ]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]]


In [55]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.cos(var2)
value

array([[-0.83907153,  0.84385396, -0.9899925 , -0.65364362],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225]])

In [56]:
var2=np.array([[10,12,3,4],[4,5,6,7,]])
value=np.cumsum(var2)
value

array([10, 22, 25, 29, 33, 38, 44, 51])

In [59]:
idx=np.array([1,2,3,5])
print(idx[::-1])


[5 3 2 1]


In [60]:
idx=np.array([1,2,3,5])
print(idx[::3])


[1 5]


In [61]:
idx=np.array([1,2,3,5])
print(idx[:3])

[1 2 3]


In [62]:
idx=np.array([1,2,3,5])
print(idx[1:4])

[2 3 5]


In [63]:
var=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(var)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [66]:
print(var[2][3])

12


In [67]:
var=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(var)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [69]:
print(var[0][0][3])

4


In [70]:
var=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(var)

for i in var:
    for k in i:
        for n in k:
            print(n)
        print()
    print()

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
1
2
3
4

5
6
7
8

9
10
11
12


