In [1]:
import numpy as np

In [5]:
var=np.array([1,2,3,4,5,5,6,])
var2=np.array([1,2,3,4,5,5,6,])
print(np.add(var,var2))

[ 2  4  6  8 10 10 12]


                                                                Copy and View

In [22]:
var=np.array([1,2,3,4,5])

print()
co=var.copy()
co[2]=40
print("Orignal:",var)
print("Copy:",co)


Orignal: [1 2 3 4 5]
Copy: [ 1  2 40  4  5]


In [23]:
x=np.array([1,2,3,4,5,6])


v1=x.view()
x[2]=40
print(x)
print("The view of x1 is:",v1)

[ 1  2 40  4  5  6]
The view of x1 is: [ 1  2 40  4  5  6]


                                                        Join and Spilit function

In [37]:
var1=np.array([[1,2,3,4,5],[31,31,33,34,35]])
var2=np.array([[11,12,13,14,15],[21,22,23,24,25]])
ar=np.concatenate((var1,var2),axis=1)	#axis 1 iterate on the rows while 0 on the columns
print(ar)

[[ 1  2  3  4  5 11 12 13 14 15]
 [31 31 33 34 35 21 22 23 24 25]]


In [39]:
var1=np.array([[1,2,3,4,5],[31,31,33,34,35]])
var2=np.array([[11,12,13,14,15],[21,22,23,24,25]])
ar=np.concatenate((var1,var2),axis=0)
print(ar)

[[ 1  2  3  4  5]
 [31 31 33 34 35]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [43]:
var_1=np.array([[1,2,3,4,5],[31,31,33,34,35]])
var_2=np.array([[11,12,13,14,15],[21,22,23,24,25]])
ar_new=np.stack((var_1,var_2),axis=1)
print(ar_new)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[31 31 33 34 35]
  [21 22 23 24 25]]]


In [44]:
import numpy as np

In [50]:
var=np.array([1,2,3,4,5])
ar=np.array_split(var,3)
print(ar)

[array([1, 2]), array([3, 4]), array([5])]


In [53]:
var=np.array([[1,2,3,4,5],[11,12,13,14,15]])
ar=np.array_split(var,3)
print(ar)
print(ar[1])

[array([[1, 2, 3, 4, 5]]), array([[11, 12, 13, 14, 15]]), array([], shape=(0, 5), dtype=int32)]
[[11 12 13 14 15]]


In [54]:
var=np.array([[1,2,3,4,5],[11,12,13,14,15]])
ar=np.array_split(var,3,axis=1)
print(ar)
print(ar[1])

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5],
       [15]])]
[[ 3  4]
 [13 14]]


                                                Search Sort and Filter

In [61]:
var=np.array([1,2,3,4,5,6,7,5,5])
result=np.where(var==5)
print(result)

(array([4, 7, 8], dtype=int64),)


In [68]:
var1=np.array([1,3,4,6,7])
result=np.searchsorted(var1,(2,5),side='right')
print(result)

[1 3]


In [72]:
var_1=np.array([5,6,3,4,1,1,7,9,8])
result=np.sort(var_1)
print(result)

[1 1 3 4 5 6 7 8 9]


In [73]:
var_1=np.array(["w","a","r","i","s"])
result=np.sort(var_1)
print(result)

['a' 'i' 'r' 's' 'w']


In [77]:
var_1=np.array([[5,6,3,4],[111,12,669,14]])
result=np.sort(var_1)
print(result)

[[  3   4   5   6]
 [ 12  14 111 669]]


                                                        filter Function

In [80]:
df=np.array([1,2,3,4])
result=[True,False,True,False]
new_result=df[2]
print(new_result)

3


                                          Some Functionlike shuffle / unique / resize/ flatten/ ravel

In [82]:
data=np.array([1,2,3,4,5,6])
np.random.shuffle(data)
data

array([4, 6, 5, 1, 3, 2])

In [88]:
new=np.array([1,2,3,4,5,1,2,8,2,0,2])
result=np.unique(new,return_index=True,return_counts=True)
print("Old Data:",new)
print("Unique:",result)

Old Data: [1 2 3 4 5 1 2 8 2 0 2]
Unique: (array([0, 1, 2, 3, 4, 5, 8]), array([9, 0, 1, 2, 3, 4, 7], dtype=int64), array([1, 2, 4, 1, 1, 1, 1], dtype=int64))


In [90]:
resize=np.array([1,2,3,4,5,6])
y=np.resize(resize,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


                                                                    INSERT AND Delet

In [107]:
var=np.array([1,2,3,4,5])
print(var.dtype)
print(var)
print(type(var))
v=np.insert(var,(1,3),222)
print(v)

int32
[1 2 3 4 5]
<class 'numpy.ndarray'>
[  1 222   2   3 222   4   5]


In [113]:
var1=np.array([[1,2,3,4],[11,12,13,14]])
print(var1)
print()
result=np.insert(var1,1,2222,axis=0)
print(result)

[[ 1  2  3  4]
 [11 12 13 14]]

[[   1    2    3    4]
 [2222 2222 2222 2222]
 [  11   12   13   14]]


In [116]:
dlt=np.array([[1,2,3,4],[11,12,13,14]])
d=np.delete(dlt,2)
print(d)

[ 1  2  4 11 12 13 14]
