In [1]:
import numpy as np

In [7]:
var=np.array([1,2,3,4,5,6])
var=var+3
var

array([4, 5, 6, 7, 8, 9])

In [8]:
var=np.array([1,2,3,4,5,6])
var=var*3
var

array([ 3,  6,  9, 12, 15, 18])

In [9]:
var=np.array([1,2,3,4,5,6])
var=var-3
var

array([-2, -1,  0,  1,  2,  3])

In [10]:
var=np.array([1,2,3,4,5,6])
var=var/3
var

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [11]:
var=np.array([1,2,3,4,5,6])
var=var**3
var

array([  1,   8,  27,  64, 125, 216], dtype=int32)

In [16]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.add(var1,var2))


[ 2  4  6  8 10 12]


In [17]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.subtract(var1,var2))

[0 0 0 0 0 0]


In [18]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.multiply(var1,var2))

[ 1  4  9 16 25 36]


In [19]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.mod(var1,var2))

[0 0 0 0 0 0]


In [21]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.divide(var1,var2))

[1. 1. 1. 1. 1. 1.]


In [22]:
var1=np.array([1,2,3,4,5,6])
var2=np.array([1,2,3,4,5,6])
print(np.reciprocal(var1,var2))

[1 0 0 0 0 0]


                                                        2D

In [25]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
print(np.add(var2,var22))

[[2 4 6 8]
 [2 4 6 8]]


In [26]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
print(np.multiply(var2,var22))

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [27]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
print(np.subtract(var2,var22))

[[0 0 0 0]
 [0 0 0 0]]


In [28]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
print(np.divide(var2,var22))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
print(np.reciprocal(var2,var22))

[[1 0 0 0]
 [1 0 0 0]]


In [45]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.min(var2),np.argmin(var2)

print("Minimum is:",var2)

Minimum is: (1, 0)


In [43]:
var2=np.array([[1,2,3,4],[1,2,3,4]])
var=np.max(var2),np.argmax(var2)
print("Max is",var)

Max is (4, 3)


                                            Axis 0 work along coloums

In [46]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.min(var1,axis=0))

[1 2 3]


                                                Axis 1 work along rows

In [48]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.min(var1,axis=1))

[1 5]


In [49]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.max(var1,axis=0))

[9 5 6]


In [50]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.max(var1,axis=1))

[3 9]


In [51]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.max(var1,axis=1))
print(np.sqrt(var1))

[3 9]
[[1.         1.41421356 1.73205081]
 [3.         2.23606798 2.44948974]]


In [52]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.mean(var1))

4.333333333333333


In [53]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.median(var1))

4.0


In [57]:
arr=np.array([1,2,3,4])
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [58]:
arr=np.array([1,2,3,4])
print(np.cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [59]:
arr=np.array([1,2,3,4])
print(np.cumsum(arr))

[ 1  3  6 10]


In [60]:
var1=np.array([[1,2,3],[9,5,6]])
print(np.cumsum(var1))

[ 1  3  6 15 20 26]


                                                            BroadCasting

In [61]:
import numpy as np

In [72]:
x=np.array([[1],[2]])
y=np.array([[1,2,3],[1,2,3]])
print(x+y)

[[2 3 4]
 [3 4 5]]


                                                        inding and slicing

In [81]:
idx=np.array([1,2,3,5])
print(idx[:-1])

[1 2 3]


In [93]:
idx=np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(idx[0][1])
print(idx[0][2])
print(idx[0][3])
print(idx[0][4])
print(idx[0][0])
print()
print(idx[1][1])
print(idx[1][2])
print(idx[1][3])
print(idx[1][4])
print(idx[1][0])
print()
print(idx[1][0:3])
print(idx[0][0:3])

2
3
4
5
1

12
13
14
15
11

[11 12 13]
[1 2 3]


In [104]:
d3=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(d3)
print(d3.ndim)
print("values",d3[0][3][1])

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
values 8


In [106]:
d2=np.array([[1,2,3,4],[5,6,7,8]])
print(d2[1][0:3])

[5 6 7]


                                                                    iteration

In [109]:
var=np.array([1,2,3,4,5,6,7,8,9])
for i in var:
    print(i)

1
2
3
4
5
6
7
8
9


In [118]:
var=np.array([[1,2,3,4,5,6,7,8,9],[12,1,3,15,16,6,7,8,9]])
print(var)
print()
for i in var:
    print(i)
print()
for k in var:
    for j in k:
        print(j)
    print()

[[ 1  2  3  4  5  6  7  8  9]
 [12  1  3 15 16  6  7  8  9]]

[1 2 3 4 5 6 7 8 9]
[12  1  3 15 16  6  7  8  9]

1
2
3
4
5
6
7
8
9

12
1
3
15
16
6
7
8
9



In [123]:
var=np.array([[[1,2,3],[12,1,3],[21,2,23]]])
for k in var:
    for j in k:
        for x in j:
            print(x)
        print()
    print()

1
2
3

12
1
3

21
2
23




                                                    iterate with function
                                                    