In [10]:
import numpy as np

ERROR: unknown command "instal" - maybe you meant "install"



In [11]:
var=np.array([1,2,3,4])
var

array([1, 2, 3, 4])

                                                        Matrix

In [17]:
arr=np.matrix([[1,2,3,4],[4,5,6,7]])
print(arr*2)
print(type(arr))

[[ 2  4  6  8]
 [ 8 10 12 14]]
<class 'numpy.matrix'>


In [20]:
var_1=np.array([[1,2,3,4],[4,5,6,7]])
print(var_1*2)
print(type(var_1))

[[ 2  4  6  8]
 [ 8 10 12 14]]
<class 'numpy.ndarray'>


In [26]:
arr1=np.matrix([[1,2],[4,5]])
arr2=np.matrix([[1,2],[4,5]])
print(arr1*arr2)
print()
print(arr1.dot(arr2))

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


In [32]:
var_1=np.array([[1,2],[4,5]])
var_2=np.array([[1,2],[4,5]])
print(var_1*var_2)
print()
print(np.multiply(var_1,var_2))

[[ 1  4]
 [16 25]]

[[ 1  4]
 [16 25]]


                                                            Matrix Function in NumPy

In [37]:
matrix=np.matrix([[1,2,3],[4,5,6]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

                                                            Transpose

In [38]:
print(np.transpose(matrix))

[[1 4]
 [2 5]
 [3 6]]


In [39]:
                                                                #Swapcase

In [43]:
print(np.swapaxes(matrix,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [44]:
                                                            #inverse

In [67]:
matrix=np.matrix([[1,2],[4,5]])
print(matrix)
print()
print(np.linalg.inv(matrix))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [66]:
var=np.matrix([[1,2,3],[4,5,3],[7,8,5]])
print(np.linalg.det(var))

-6.0
